style: changelog
<changelog>
  <title-maps>
    <feat>新功能</feat>
    <fix>Bug 修复</fix>
    <docs>文档更新</docs>
    <style>代码格式</style>
    <refactor>重构</refactor>
    <perf>性能优化</perf>
    <test>测试</test>
    <build>构建系统</build>
    <ci>CI/CD</ci>
    <chore>其他</chore>
  </title-maps>

  <header>
    # 更新日志

    本项目的所有重要更改都将记录在此文件中。

    格式基于 [Keep a Changelog](https://keepachangelog.com/zh-CN/1.0.0/)，
    本项目遵循 [语义化版本](https://semver.org/lang/zh-CN/)。
  </header>

  <body>
    {{if .Versions -}}
    <a name="unreleased"></a>
    ## [Unreleased]

    {{ range .Versions }}
    <a name="{{ .Tag.Name }}"></a>
    ## {{ if .Tag.Previous }}[{{ .Tag.Name }}]{{ else }}{{ .Tag.Name }}{{ end }} - {{ datetime "2006-01-02" .Tag.Date }}
    {{ range .CommitGroups -}}
    ### {{ .Title }}
    {{ range .Commits -}}
    - {{ if .Scope }}**{{ .Scope }}:** {{ end }}{{ .Subject }}
    {{ end }}
    {{ end -}}

    {{- if .RevertCommits -}}
    ### Reverts
    {{ range .RevertCommits -}}
    - {{ .Revert.Header }}
    {{ end }}
    {{ end -}}

    {{- if .MergeCommits -}}
    ### Pull Requests
    {{ range .MergeCommits -}}
    - {{ .Header }}
    {{ end }}
    {{ end -}}

    {{- if .NoteGroups -}}
    {{ range .NoteGroups -}}
    ### {{ .Title }}
    {{ range .Notes }}
    {{ .Body }}
    {{ end }}
    {{ end -}}
    {{ end -}}
    {{ end -}}
    {{- end -}}

    {{- if .Versions }}
    [Unreleased]: {{ .Info.RepositoryURL }}/compare/{{ $latest := index .Versions 0 }}{{ $latest.Tag.Name }}...HEAD
    {{ range .Versions -}}
    {{ if .Tag.Previous -}}
    [{{ .Tag.Name }}]: {{ $.Info.RepositoryURL }}/compare/{{ .Tag.Previous.Name }}...{{ .Tag.Name }}
    {{ end -}}
    {{ end -}}
    {{ end -}}
  </body>
</changelog>
